
kind: Deployment
apiVersion: apps/v1
metadata:
  name: doctor
  labels:
    module: doctor
spec:
  replicas: 1
  selector:
    matchLabels:
      module: doctor
  template:
    metadata:
      labels:
        module: doctor
    spec:
      containers:
        - name: doctor
          image: docker.io/stephanzlatarev/norman-gym-doctor
          imagePullPolicy: Always
          env:
            - name: VERSION
              value: "0"
