
kind: Deployment
apiVersion: apps/v1
metadata:
  name: trainer-looney
  labels:
    module: trainer-looney
spec:
  replicas: 1
  selector:
    matchLabels:
      module: trainer-looney
  template:
    metadata:
      labels:
        module: trainer-looney
    spec:
      containers:
        - name: trainer-looney
          image: docker.io/stephanzlatarev/norman-gym-trainer
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
          env:
            - name: BRAIN
              value: "looney"
            - name: MODE
              value: "flow"
            - name: SCALE
              value: "1"
            - name: VERSION
              value: "0"

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: trainer-brain
  labels:
    module: trainer-brain
spec:
  replicas: 1
  selector:
    matchLabels:
      module: trainer-brain
  template:
    metadata:
      labels:
        module: trainer-brain
    spec:
      containers:
        - name: trainer
          image: docker.io/stephanzlatarev/norman-gym-trainer
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
          env:
            - name: BRAIN
              value: "brain"
            - name: MODE
              value: "flow"
            - name: SCALE
              value: "2"
            - name: VERSION
              value: "0"

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: trainer-pinky
  labels:
    module: trainer-pinky
spec:
  replicas: 1
  selector:
    matchLabels:
      module: trainer-pinky
  template:
    metadata:
      labels:
        module: trainer-pinky
    spec:
      containers:
        - name: trainer
          image: docker.io/stephanzlatarev/norman-gym-trainer
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
          env:
            - name: BRAIN
              value: "pinky"
            - name: MODE
              value: "flow"
            - name: SCALE
              value: "4"
            - name: VERSION
              value: "0"
