
kind: Deployment
apiVersion: apps/v1
metadata:
  name: trainer
  labels:
    module: trainer
spec:
  replicas: 1
  selector:
    matchLabels:
      module: trainer
  template:
    metadata:
      labels:
        module: trainer
    spec:
      containers:
        - name: trainer
          image: docker.io/stephanzlatarev/norman-gym-trainer
          imagePullPolicy: Always
          resources:
            requests:
              memory: "2Gi"
              cpu: "250m"
          env:
            - name: VERSION
              value: "4"
