
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: trainer
  labels:
    module: trainer
spec:
  replicas: 8
  selector:
    matchLabels:
      module: trainer
  serviceName: "trainer"
  template:
    metadata:
      labels:
        module: trainer
    spec:
      containers:
        - name: trainer
          image: docker.io/stephanzlatarev/norman-gym-trainer
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
          env:
            - name: VERSION
              value: "0"
