kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: web
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: ngym.ddns.net
      http:
        paths:
          - backend:
              service:
                name: web
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - ngym.ddns.net
      secretName: https

---

kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  selector:
    module: web
  ports:
    - name: http
      port: 80
      targetPort: 80

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
  labels:
    module: web
spec:
  replicas: 1
  selector:
    matchLabels:
      module: web
  template:
    metadata:
      labels:
        module: web
    spec:
      containers:
        - name: web
          image: docker.io/stephanzlatarev/norman-gym-web
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VERSION
              value: "0"
